{% set version = '1.9.1' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-wfe
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/wfe_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/wfe/wfe_{{ version }}.tar.gz
  sha256: 3a1ed72086a01622ea5290e361a546b08463493569cee679c33c50da3e3c8f51

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - {{ compiler('c') }}        # [not win]
    - {{ stdlib("c") }}          # [not win]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ stdlib("m2w64_c") }}    # [win]
    - {{ posix }}filesystem      # [win]
    - {{ posix }}make
    - {{ posix }}sed             # [win]
    - {{ posix }}coreutils       # [win]
    - {{ posix }}zip             # [win]
  host:
    - r-base
    - r-arm
    - r-mass
    - r-matrix
  run:
    - r-base
    - r-arm
    - r-mass
    - r-matrix

test:
  commands:
    - $R -e "library('wfe')"           # [not win]
    - "\"%R%\" -e \"library('wfe')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=wfe
  dev_url: https://github.com/insongkim/wfe
  license: GPL-2.0-or-later
  summary: Provides a computationally efficient way of fitting weighted linear fixed effects
    estimators for causal inference with various weighting schemes. Weighted linear
    fixed effects estimators can be used to estimate the average treatment effects under
    different identification strategies. This includes stratified randomized experiments,
    matching and stratification for observational studies, first differencing, and difference-in-differences.
    The package implements methods described in Imai and Kim (2017) "When should We
    Use Linear Fixed Effects Regression Models for Causal Inference with Longitudinal
    Data?", available at <https://imai.fas.harvard.edu/research/FEmatch.html>.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: wfe
# Type: Package
# Title: Weighted Linear Fixed Effects Regression Models for Causal Inference
# Version: 1.9.1
# Date: 2019-04-17
# Authors@R: c( person("In Song", "Kim", email = "insong@mit.edu", role = c("aut", "cre")), person("Kosuke", "Imai", email = "imai@Harvard.edu", role = c("aut")) )
# Description: Provides a computationally efficient way of fitting weighted linear fixed effects estimators for causal inference with various weighting schemes. Weighted linear fixed effects estimators can be used to estimate the average treatment effects under different identification strategies. This includes stratified randomized experiments, matching and stratification for observational studies, first differencing, and difference-in-differences. The package implements methods described in Imai and Kim (2017) "When should We Use Linear Fixed Effects Regression Models for Causal Inference with Longitudinal Data?", available at <https://imai.fas.harvard.edu/research/FEmatch.html>.
# License: GPL (>= 2)
# Imports: utils, arm, Matrix, MASS, methods
# Depends: R (>= 3.2.0)
# Encoding: UTF-8
# LazyData: true
# BugReports: https://github.com/insongkim/wfe/issues
# NeedsCompilation: yes
# Packaged: 2019-04-17 21:25:40 UTC; insong
# Author: In Song Kim [aut, cre], Kosuke Imai [aut]
# Maintainer: In Song Kim <insong@mit.edu>
# Repository: CRAN
# Date/Publication: 2019-04-17 21:50:03 UTC
